import Link from "next/link";
import { BadgeCheck, FileCheck2, Fingerprint, Globe2, ScanSearch, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const features = [[FileCheck2, "Consent releases", "Creators record where, how long, and for what campaign their work may be used."], [Globe2, "Usage evidence", "Publishers submit the live media, campaign page, or ad URL that needs checking."], [ScanSearch, "Semantic review", "GenLayer validators compare the published use with the creator's written consent terms."], [BadgeCheck, "Verifiable verdicts", "The contract stores the match decision, confidence, reasoning, and review history."], [ShieldCheck, "Abstention by design", "Unclear or unreachable evidence becomes UNDETERMINED instead of a made-up yes or no."], [Fingerprint, "Built for repeat use", "Testimonials, UGC ads, campaign clips, podcasts, and branded creator work fit the same gate."]] as const;

export default function LandingPage() {
  return <div className="space-y-16"><section className="grid items-center gap-8 pt-8 lg:grid-cols-[1.05fr_0.95fr]"><div><p className="mb-4 inline-block rounded-full border border-amberline/70 px-4 py-1 text-xs uppercase tracking-[0.28em] text-amberline">CONSENT TERMINAL · GENLAYER STUDIONET</p><h1 className="max-w-4xl text-4xl font-black leading-tight text-vault-100 md:text-6xl">Consent before the clip goes live.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-vault-200">ConsentClip gives creators and publishers a shared release record before a video, testimonial, or UGC ad is published. If the final use is disputed, GenLayer reads the media and the terms and decides whether they match.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/cases/new"><Button size="lg">Create a release</Button></Link><Link href="/cases"><Button size="lg" variant="outline">Browse releases</Button></Link></div></div><Card><CardHeader><p className="font-mono text-xs uppercase tracking-[0.24em] text-vault-700">Live workflow</p><CardTitle>Terms → publish → review → verdict</CardTitle></CardHeader><CardContent><div className="grid gap-3">{[["01", "Creator defines the media, campaign, channels, and expiry."], ["02", "Publisher uses the work under the recorded release."], ["03", "Either party submits the live usage URL and context."], ["04", "GenLayer decides whether the published use matches consent."]].map(([step, text]) => <div key={step} className="flex gap-3 rounded-md border border-vault-700/20 p-3"><span className="font-mono text-sm font-black text-vault-700">{step}</span><p className="text-sm text-vault-950/75">{text}</p></div>)}</div></CardContent></Card></section><section className="grid gap-4 md:grid-cols-3">{features.map(([Icon, title, text]) => <Card key={title}><CardHeader><Icon className="mb-2 h-7 w-7 text-vault-700" /><CardTitle>{title}</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-vault-950/75">{text}</p></CardContent></Card>)}</section><section className="rounded-lg border border-vault-300/15 bg-vault-900/80 p-8"><div className="grid gap-4 lg:grid-cols-[1fr_auto] lg:items-center"><div><h2 className="text-2xl font-black">Consent matching is not a regex.</h2><p className="mt-3 max-w-3xl text-vault-200">A normal app can check whether a URL exists, but not whether a creator&apos;s face, words, edit, placement, or campaign context stays inside the permission they granted. That semantic question belongs in GenLayer consensus.</p></div><Link href="/dashboard"><Button variant="secondary">Open release desk</Button></Link></div></section></div>;
}
